import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed with 23 Budgies + 17 Lovebirds + 5 Cockatiels + 5 Sun Conures + 3 Finches + 7 Real Cages + Jute Nest & Clay Nesting Pots...');

  // 1. Clean existing data
  await prisma.review.deleteMany({});
  await prisma.orderItem.deleteMany({});
  await prisma.order.deleteMany({});
  await prisma.cartItem.deleteMany({});
  await prisma.wishlistItem.deleteMany({});
  await prisma.productImage.deleteMany({});
  await prisma.product.deleteMany({});
  await prisma.category.deleteMany({});
  await prisma.bird.deleteMany({});
  await prisma.coupon.deleteMany({});
  await prisma.blogPost.deleteMany({});
  await prisma.contactMessage.deleteMany({});
  await prisma.siteSetting.deleteMany({});
  await prisma.address.deleteMany({});
  await prisma.user.deleteMany({});

  // 2. Users
  const adminPassword = await bcrypt.hash('admin123', 10);
  const userPassword = await bcrypt.hash('user123', 10);

  await prisma.user.create({
    data: {
      name: 'Aviary Admin',
      email: 'admin@aviary.com',
      passwordHash: adminPassword,
      role: 'ADMIN',
      phone: '+91 98765 43210',
    },
  });

  await prisma.user.create({
    data: {
      name: 'Rohan Sharma',
      email: 'customer@aviary.com',
      passwordHash: userPassword,
      role: 'CUSTOMER',
      phone: '+91 98123 45678',
      addresses: {
        create: {
          street: '42 Feather Lane, Green Park',
          city: 'New Delhi',
          state: 'Delhi',
          pincode: '110016',
          isDefault: true,
        },
      },
    },
  });

  console.log('✅ Created Admin & Customer Accounts');

  // 3. Site Settings
  const defaultSettings = [
    { key: 'site_name', value: 'Feather Haven Aviary & Pet Shop' },
    { key: 'hero_title', value: 'Find Your Perfect Feathered Companion' },
    { key: 'hero_subtitle', value: 'Healthy, hand-reared Budgies (23 varieties), Lovebirds (17 varieties), Cockatiels (5 varieties), Sun Conures (5 varieties) & Finches (3 varieties) with premium Pet Bar Barky cages, nest boxes, and gourmet seed mixes.' },
    { key: 'announcement_bar', value: '🎉 Free express delivery on orders over ₹1,999! Use coupon WELCOME10 for 10% OFF.' },
    { key: 'whatsapp_number', value: '919876543210' },
    { key: 'store_address', value: 'Shop #14, Royal Palm Arcade, MG Road, Bengaluru, Karnataka 560001' },
    { key: 'store_hours', value: 'Mon - Sun: 9:30 AM - 8:30 PM' },
  ];

  for (const s of defaultSettings) {
    await prisma.siteSetting.create({ data: s });
  }

  // 4. Categories
  const cagesCat = await prisma.category.create({
    data: {
      name: 'Bird Cages',
      slug: 'cages',
      description: 'Spacious, safe, and durable cages for parakeets, cockatiels, and small birds.',
      image: '/images/products/cage_medium_30x18x24.png',
    },
  });

  const foodCat = await prisma.category.create({
    data: {
      name: 'Bird Food & Seeds',
      slug: 'food',
      description: 'Authentic wholesome bird seeds (seed) and fortified 11-in-1 grain blends (seed_mix).',
      image: '/images/products/seed_mix_11_15_grains.webp',
    },
  });

  const accessoriesCat = await prisma.category.create({
    data: {
      name: 'Accessories & Toys',
      slug: 'accessories',
      description: 'Interactive swings, perches, feeders, water fountains, and nesting boxes.',
      image: '/images/products/nest_handcrafted_jute.jpg',
    },
  });

  // 5. Individual Birds - 23 BUDGIES + 17 LOVEBIRDS + 5 COCKATIELS + 5 SUN CONURES + 3 VERIFIED USER FINCHES
  const birdsData = [
    // --- BUDGIES (23 VARIETIES) ---
    {
      birdCode: 'BDG-101',
      name: 'Classic Wild Type Normal Green Budgie',
      slug: 'classic-wild-type-normal-green-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Normal Green',
      color: 'Emerald Green Body, Yellow Face, Black Scallops',
      age: '4 Months',
      gender: 'Male',
      price: 1100,
      status: 'AVAILABLE',
      healthStatus: 'Active & Vet Checked',
      healthInfo: 'De-wormed, bright plumage, active chirping.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Millet seeds, fresh spinach, calcium block.',
      temperament: 'Gentle, curious, hand-tame ready.',
      description: 'Classic wild-type appearance: emerald green body, yellow face, and classic black wing markings.',
      images: JSON.stringify(['/images/birds/bdg-101.webp']),
    },
    {
      birdCode: 'BDG-102',
      name: 'Yellowface Sky Blue Parakeet',
      slug: 'yellowface-sky-blue-parakeet',
      species: 'Budgerigar / Parakeet',
      variety: 'Yellowface',
      color: 'Bright Lemon Face & Ocean Blue',
      age: '5 Months',
      gender: 'Female',
      price: 1350,
      status: 'AVAILABLE',
      healthStatus: 'Fully Vaccinated',
      healthInfo: 'Strong wing feather growth and high vitality.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Seed mix, fresh cut apples, millet spray.',
      temperament: 'Playful & Vocal',
      description: 'Blue-series budgie with a brilliant yellow face; giving a soft turquoise sea-green glow.',
      images: JSON.stringify(['/images/birds/bdg-102.png']),
    },
    {
      birdCode: 'BDG-103',
      name: 'Clearwing Cobalt Budgie',
      slug: 'clearwing-cobalt-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Clearwing',
      color: 'Pure White Wings & Deep Cobalt Body',
      age: '4.5 Months',
      gender: 'Male',
      price: 1450,
      status: 'AVAILABLE',
      healthStatus: 'Healthy & Energetic',
      healthInfo: 'High energy levels, hand-tame ready.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Fortified seed mix + green leafy vegetables.',
      temperament: 'Friendly & Quick Learner',
      description: 'Bright body color with very pale, almost clear un-marked wing feathers.',
      images: JSON.stringify(['/images/birds/bdg-103.png']),
    },
    {
      birdCode: 'BDG-104',
      name: 'Sunshine Lutino Budgie (Pure Yellow)',
      slug: 'sunshine-lutino-budgie-pure-yellow',
      species: 'Budgerigar / Parakeet',
      variety: 'Lutino',
      color: 'Buttercup Yellow & Red/Pink Eyes',
      age: '5 Months',
      gender: 'Female',
      price: 1500,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified',
      healthInfo: 'Ruby eyes, smooth plumage.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Pellets, millet spray, calcium block.',
      temperament: 'Sweet & Affectionate',
      description: 'Bright yellow body with characteristic red/pink eyes and soft white cheek patches.',
      images: JSON.stringify(['/images/birds/bdg-104.jpg']),
    },
    {
      birdCode: 'BDG-105',
      name: 'Albino Snow White Budgie (Pearl)',
      slug: 'albino-snow-white-budgie-pearl',
      species: 'Budgerigar / Parakeet',
      variety: 'Albino',
      color: 'Pure White & Red/Pink Eyes',
      age: '5.5 Months',
      gender: 'Female',
      price: 1650,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Immaculate white plumage and strong beak posture.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'High-protein seed mix & calcium block.',
      temperament: 'Calm & Graceful',
      description: 'Completely snow-white with red/pink eyes. Completely free of dark melanin pigmentation.',
      images: JSON.stringify(['/images/birds/bdg-105.png']),
    },
    {
      birdCode: 'BDG-106',
      name: 'Cobalt Violet Opaline Budgie',
      slug: 'cobalt-violet-opaline-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Opaline',
      color: 'Violet-Blue V-Shape Back',
      age: '6 Months',
      gender: 'Male',
      price: 1750,
      status: 'AVAILABLE',
      healthStatus: 'Show Quality',
      healthInfo: 'Extremely vocal, loves whistling.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Varied seeds + sprout salad.',
      temperament: 'Curious & Whistling',
      description: 'Reduced head and mantle wing markings with more rich body color showing through.',
      images: JSON.stringify(['/images/birds/bdg-106.png']),
    },
    {
      birdCode: 'BDG-107',
      name: 'Golden Spangle Olive Budgie',
      slug: 'golden-spangle-olive-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Spangle',
      color: 'Scalloped Gold & Olive Green',
      age: '4 Months',
      gender: 'Male',
      price: 1600,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Active flyer.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Seed mix & egg food.',
      temperament: 'Energetic',
      description: 'Distinctive reversed/light wing markings: fine black rings edging golden yellow feathers.',
      images: JSON.stringify(['/images/birds/bdg-107.png']),
    },
    {
      birdCode: 'BDG-108',
      name: 'Harlequin Recessive Pied Budgie',
      slug: 'harlequin-recessive-pied-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Pied',
      color: 'Patchwork White & Blue Violet',
      age: '5 Months',
      gender: 'Female',
      price: 1550,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'De-wormed.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Standard seed mix + cucumber.',
      temperament: 'Gentle',
      description: 'Irregular patches of white/yellow mixed with the body color.',
      images: JSON.stringify(['/images/birds/bdg-108.png']),
    },
    {
      birdCode: 'BDG-109',
      name: 'Soft Cinnamon Green Budgie',
      slug: 'soft-cinnamon-green-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Cinnamon',
      color: 'Cinnamon Brown Wings & Soft Green',
      age: '6 Months',
      gender: 'Male',
      price: 1700,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Clean beak and vent.',
      careLevel: 'Beginner',
      dietRecommendation: 'Pellet seed mix + grated carrots.',
      temperament: 'Quiet',
      description: 'Brownish wing markings instead of standard black.',
      images: JSON.stringify(['/images/birds/bdg-109.png']),
    },
    {
      birdCode: 'BDG-110',
      name: 'Turquoise Crested Tufted Budgie',
      slug: 'turquoise-crested-tufted-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Crested',
      color: 'Circular Crest & Seafoam Turquoise',
      age: '7 Months',
      gender: 'Male',
      price: 2600,
      status: 'AVAILABLE',
      healthStatus: 'Rare Nursery Mutation',
      healthInfo: 'Perfect head tuft crest rosette.',
      careLevel: 'Intermediate',
      dietRecommendation: 'High energy seed blend.',
      temperament: 'Regal & Friendly',
      description: 'A rare crested mutation featuring a circular feather rosette crest atop its head.',
      images: JSON.stringify(['/images/birds/bdg-110.webp']),
    },
    {
      birdCode: 'BDG-111',
      name: 'Jumbo English Exhibition Budgie',
      slug: 'jumbo-english-exhibition-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'English Exhibition',
      color: 'Large Head Fluff & Forest Green',
      age: '7.5 Months',
      gender: 'Male',
      price: 2900,
      status: 'AVAILABLE',
      healthStatus: 'Exhibition Pedigree',
      healthInfo: 'Robust frame, show stance.',
      careLevel: 'Beginner / Enthusiast',
      dietRecommendation: 'High protein seed + egg biscuits.',
      temperament: 'Calm & Gentle Giant',
      description: 'Larger English Show Budgie breed boasting fluffy forehead cap and deep throat spots.',
      images: JSON.stringify(['/images/birds/bdg-111.jpg']),
    },
    {
      birdCode: 'BDG-112',
      name: 'Pastel Rainbow Mutation Budgerigar',
      slug: 'pastel-rainbow-mutation-budgerigar',
      species: 'Budgerigar / Parakeet',
      variety: 'Rainbow',
      color: 'Blended Yellow, Blue, Violet & Opaline',
      age: '4.5 Months',
      gender: 'Male',
      price: 2800,
      status: 'AVAILABLE',
      healthStatus: 'Superb Plumage',
      healthInfo: 'Hand-tame and highly active.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Seed mix + vitamin drop water.',
      temperament: 'Playful & Cuddle Bug',
      description: 'The coveted Rainbow Budgie combining Yellowface, Opaline, Clearwing, and Cobalt Blue.',
      images: JSON.stringify(['/images/birds/bdg-112.jpg']),
    },
    {
      birdCode: 'BDG-113',
      name: 'Classic Sky Blue Budgie',
      slug: 'classic-sky-blue-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Sky Blue',
      color: 'Light Blue Body with White Face',
      age: '4 Months',
      gender: 'Male',
      price: 1250,
      status: 'AVAILABLE',
      healthStatus: 'Active & Healthy',
      healthInfo: 'Clear eyes, active flying.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Seed mix, millet spray, calcium block.',
      temperament: 'Friendly',
      description: 'Light blue body with clean white face and standard black scalloped wing markings.',
      images: JSON.stringify(['/images/birds/bdg-113.jpg']),
    },
    {
      birdCode: 'BDG-114',
      name: 'Deep Cobalt Blue Budgie',
      slug: 'deep-cobalt-blue-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Cobalt Blue',
      color: 'Deeper Blue Body with White Face',
      age: '5 Months',
      gender: 'Female',
      price: 1400,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified',
      healthInfo: 'Rich cobalt plumage.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Daily seed blend & fresh greens.',
      temperament: 'Playful',
      description: 'Rich, deeper blue body than sky blue with clean white face mask.',
      images: JSON.stringify(['/images/birds/bdg-114.webp']),
    },
    {
      birdCode: 'BDG-115',
      name: 'Smoky Mauve Budgie',
      slug: 'smoky-mauve-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Mauve',
      color: 'Dark Greyish-Blue Body',
      age: '6 Months',
      gender: 'Male',
      price: 1600,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'De-wormed.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Balanced seed mix.',
      temperament: 'Quiet & Sweet',
      description: 'Elegant dark greyish-blue body color, created by double dark factor genes.',
      images: JSON.stringify(['/images/birds/bdg-115.jpg']),
    },
    {
      birdCode: 'BDG-116',
      name: 'Vibrant Violet Factor Budgie',
      slug: 'vibrant-violet-factor-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Violet',
      color: 'Deep Blue/Purple Body',
      age: '5.5 Months',
      gender: 'Female',
      price: 1750,
      status: 'AVAILABLE',
      healthStatus: 'Show Quality',
      healthInfo: 'Vivid purple chest feathers.',
      careLevel: 'Beginner Friendly',
      dietRecommendation: 'Seed mix + egg supplement.',
      temperament: 'Energetic',
      description: 'Striking blue/purple-looking body color showcasing intense violet factor.',
      images: JSON.stringify(['/images/birds/bdg-116.jpg']),
    },
    {
      birdCode: 'BDG-117',
      name: 'Silver Grey Budgie',
      slug: 'silver-grey-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Grey',
      color: 'Slate Grey Body with Normal Markings',
      age: '5 Months',
      gender: 'Male',
      price: 1450,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Clean beak.',
      careLevel: 'Beginner',
      dietRecommendation: 'Seed blend.',
      temperament: 'Calm',
      description: 'Grey body with normal black scalloped wing markings and white face.',
      images: JSON.stringify(['/images/birds/bdg-117.png']),
    },
    {
      birdCode: 'BDG-118',
      name: 'Soft Greywing Sky Blue Budgie',
      slug: 'soft-greywing-sky-blue-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Greywing',
      color: 'Soft Grey Wing Markings & Diluted Blue',
      age: '4.5 Months',
      gender: 'Female',
      price: 1500,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Active flyer.',
      careLevel: 'Beginner',
      dietRecommendation: 'Millet & seed blend.',
      temperament: 'Gentle',
      description: 'Softer smoky grey wing markings and diluted body color.',
      images: JSON.stringify(['/images/birds/bdg-118.png']),
    },
    {
      birdCode: 'BDG-119',
      name: 'Pastel Dilute Yellow-Green Budgie',
      slug: 'pastel-dilute-yellow-green-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Dilute',
      color: 'Very Pale Soft Green & Faded Markings',
      age: '5 Months',
      gender: 'Male',
      price: 1400,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Soft feathering.',
      careLevel: 'Beginner',
      dietRecommendation: 'Seed mix.',
      temperament: 'Quiet',
      description: 'Very pale version of the normal body color with washed-out wing markings.',
      images: JSON.stringify(['/images/birds/bdg-119.png']),
    },
    {
      birdCode: 'BDG-120',
      name: 'Intense Goldenface Cobalt Budgie',
      slug: 'intense-goldenface-cobalt-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Goldenface',
      color: 'Deep Golden Yellow Face & Cobalt Body',
      age: '6 Months',
      gender: 'Male',
      price: 1850,
      status: 'AVAILABLE',
      healthStatus: 'High Vitality',
      healthInfo: 'Deep golden head cap.',
      careLevel: 'Beginner / Enthusiast',
      dietRecommendation: 'Seeds & fresh veggies.',
      temperament: 'Vocal',
      description: 'Stronger/deeper golden yellow face than typical yellowface, bleeding into body plumage.',
      images: JSON.stringify(['/images/birds/bdg-120.png']),
    },
    {
      birdCode: 'BDG-121',
      name: 'Texas Clearbody Yellow Budgie',
      slug: 'texas-clearbody-yellow-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Texas Clearbody',
      color: 'Clear Pale Yellow Body with Normal Black Markings',
      age: '6.5 Months',
      gender: 'Female',
      price: 2200,
      status: 'AVAILABLE',
      healthStatus: 'Rare Breeder Line',
      healthInfo: 'Striking contrast markings.',
      careLevel: 'Intermediate',
      dietRecommendation: 'High protein seed + minerals.',
      temperament: 'Alert & Friendly',
      description: 'Pale/clear body with contrasting stronger normal-looking black wing markings.',
      images: JSON.stringify(['/images/birds/bdg-121.png']),
    },
    {
      birdCode: 'BDG-122',
      name: 'Sunshine Lacewing Yellow Budgie',
      slug: 'sunshine-lacewing-yellow-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Lacewing',
      color: 'Yellow Body, Light Brown Wings & Reddish Eyes',
      age: '5 Months',
      gender: 'Female',
      price: 2400,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified Rare',
      healthInfo: 'Reddish eyes, cinnamon lace wings.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix, pellets, calcium.',
      temperament: 'Sweet',
      description: 'Bright yellow or white body with delicate light brown lacework wing markings and reddish eyes.',
      images: JSON.stringify(['/images/birds/bdg-122.png']),
    },
    {
      birdCode: 'BDG-123',
      name: 'Hagoromo Helicopter Feathered Budgie',
      slug: 'hagoromo-helicopter-feathered-budgie',
      species: 'Budgerigar / Parakeet',
      variety: 'Hagoromo / Helicopter',
      color: 'Japanese Flower Swirl Back Feathers & Emerald Green',
      age: '6 Months',
      gender: 'Male',
      price: 3500,
      status: 'AVAILABLE',
      healthStatus: 'Rare Exotic Pedigree',
      healthInfo: 'Double back flower swirls, active flying.',
      careLevel: 'Enthusiast',
      dietRecommendation: 'Gourmet seed blend & egg food.',
      temperament: 'Regal & Whistling',
      description: 'Prized Japanese Hagoromo Helicopter mutation featuring unique flower-like feather swirls on its back and wing crests.',
      images: JSON.stringify(['/images/birds/hagoromo_1.png', '/images/birds/hagoromo_2.png']),
    },

    // --- 17 VERIFIED USER LOVEBIRD VARIETIES ---
    {
      birdCode: 'LVB-201',
      name: 'Peach-faced Lovebird',
      slug: 'peach-faced-lovebird',
      species: 'Lovebird',
      variety: 'Peach-faced',
      color: 'Sunset Peach Mask & Emerald Body',
      age: '6 Months',
      gender: 'Male',
      price: 2800,
      status: 'AVAILABLE',
      healthStatus: 'Hand-Fed & Tame',
      healthInfo: 'Shoulder rider, zero biting.',
      careLevel: 'Beginner / Intermediate',
      dietRecommendation: 'Lovebird seed mix, fresh corn, apple slices.',
      temperament: 'Affectionate & Pocket Companion',
      description: 'Classic Peach-faced Lovebird with vibrant red-peach facial mask.',
      images: JSON.stringify(['/images/birds/lvb_peach_faced.png']),
    },
    {
      birdCode: 'LVB-202',
      name: 'Fischer’s Lovebird',
      slug: 'fischers-lovebird',
      species: 'Lovebird',
      variety: 'Fischer’s',
      color: 'Bright Orange Head & Emerald Body',
      age: '8 Months',
      gender: 'Pair (Male & Female)',
      price: 4900,
      status: 'AVAILABLE',
      healthStatus: 'Bonded Pair',
      healthInfo: 'High vitality, bonded pair.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Fortified seed mix + egg food.',
      temperament: 'Inseparable & Chirpy',
      description: 'Fischer’s Lovebird featuring a bright orange head, white eye-rings, and emerald body.',
      images: JSON.stringify(['/images/birds/lvb_fischers.png']),
    },
    {
      birdCode: 'LVB-203',
      name: 'Masked Lovebird',
      slug: 'masked-lovebird',
      species: 'Lovebird',
      variety: 'Masked',
      color: 'Coal Black Mask, Yellow Collar & Green Body',
      age: '7 Months',
      gender: 'Female',
      price: 3200,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified',
      healthInfo: 'Distinctive white eye ring.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Lovebird seed blend.',
      temperament: 'Curious & Alert',
      description: 'Striking coal-black mask with vivid yellow chest collar and white eye ring.',
      images: JSON.stringify(['/images/birds/lvb_masked.png']),
    },
    {
      birdCode: 'LVB-205',
      name: 'Lutino Lovebird',
      slug: 'lutino-lovebird',
      species: 'Lovebird',
      variety: 'Lutino',
      color: 'Bright Yellow Body & Red Mask',
      age: '6 Months',
      gender: 'Female',
      price: 3400,
      status: 'AVAILABLE',
      healthStatus: 'Hand Tame',
      healthInfo: 'Vivid yellow body.',
      careLevel: 'Beginner / Intermediate',
      dietRecommendation: 'Pellet seed mix + fruits.',
      temperament: 'Sweet',
      description: 'All-yellow plumage with a bright crimson red face mask.',
      images: JSON.stringify(['/images/birds/lvb_lutino.png']),
    },
    {
      birdCode: 'LVB-206',
      name: 'Albino Lovebird',
      slug: 'albino-lovebird',
      species: 'Lovebird',
      variety: 'Albino',
      color: 'Pure White & Red Eyes',
      age: '7 Months',
      gender: 'Male',
      price: 3800,
      status: 'AVAILABLE',
      healthStatus: 'Vet Checked',
      healthInfo: 'Ruby red eyes, immaculate white.',
      careLevel: 'Intermediate',
      dietRecommendation: 'High energy seeds.',
      temperament: 'Calm',
      description: 'Snow-white Albino lovebird mutation with ruby red eyes.',
      images: JSON.stringify(['/images/birds/lvb_albino.png']),
    },
    {
      birdCode: 'LVB-207',
      name: 'Creamino Lovebird',
      slug: 'creamino-lovebird',
      species: 'Lovebird',
      variety: 'Creamino',
      color: 'Soft Cream Body & Apricot Orange Mask',
      age: '6.5 Months',
      gender: 'Female',
      price: 3600,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Soft pastel feathering.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix & calcium.',
      temperament: 'Gentle',
      description: 'Creamy ivory-white body with delicate apricot orange facial mask.',
      images: JSON.stringify(['/images/birds/lvb_creamino.png']),
    },
    {
      birdCode: 'LVB-208',
      name: 'Blue Lovebird',
      slug: 'blue-lovebird',
      species: 'Lovebird',
      variety: 'Blue',
      color: 'Vivid Sky Blue Body & White Collar',
      age: '5.5 Months',
      gender: 'Male',
      price: 3500,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Active flyer.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix + veggies.',
      temperament: 'Playful',
      description: 'Vivid sky-blue body with dark grey head mask and white chest collar.',
      images: JSON.stringify(['/images/birds/lvb_blue.png']),
    },
    {
      birdCode: 'LVB-209',
      name: 'Cobalt Blue Lovebird',
      slug: 'cobalt-blue-lovebird',
      species: 'Lovebird',
      variety: 'Cobalt Blue',
      color: 'Deep Cobalt Navy & White Chest',
      age: '6 Months',
      gender: 'Female',
      price: 3700,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified',
      healthInfo: 'Deep dark factor blue.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix.',
      temperament: 'Vocal',
      description: 'Deeper navy cobalt blue body color featuring contrast white chest ring.',
      images: JSON.stringify(['/images/birds/lvb_cobalt_blue.png']),
    },
    {
      birdCode: 'LVB-210',
      name: 'Violet Lovebird',
      slug: 'violet-lovebird',
      species: 'Lovebird',
      variety: 'Violet',
      color: 'Rich Violet Purple Body',
      age: '7 Months',
      gender: 'Male',
      price: 4200,
      status: 'AVAILABLE',
      healthStatus: 'Show Quality',
      healthInfo: 'Intense purple violet chest.',
      careLevel: 'Intermediate',
      dietRecommendation: 'High protein seed + minerals.',
      temperament: 'Energetic',
      description: 'Exquisite deep violet purple body color with crisp white eye ring.',
      images: JSON.stringify(['/images/birds/lvb_violet.png']),
    },
    {
      birdCode: 'LVB-212',
      name: 'Pied Lovebird',
      slug: 'pied-lovebird',
      species: 'Lovebird',
      variety: 'Pied',
      color: 'Patchwork Yellow & Green',
      age: '5 Months',
      gender: 'Male',
      price: 3300,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'De-wormed.',
      careLevel: 'Beginner / Intermediate',
      dietRecommendation: 'Seed mix & fruits.',
      temperament: 'Curious',
      description: 'Striking patchwork patches of buttercup yellow randomly over green body.',
      images: JSON.stringify(['/images/birds/lvb_pied.png']),
    },
    {
      birdCode: 'LVB-213',
      name: 'Opaline Lovebird',
      slug: 'opaline-lovebird',
      species: 'Lovebird',
      variety: 'Opaline',
      color: 'Red Head Cap Extending to Nape',
      age: '6 Months',
      gender: 'Female',
      price: 3800,
      status: 'AVAILABLE',
      healthStatus: 'High Vitality',
      healthInfo: 'Clear opaline hood.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed blend.',
      temperament: 'Sweet',
      description: 'Opaline mutation extending the red facial mask completely back over the head.',
      images: JSON.stringify(['/images/birds/lvb_opaline.png']),
    },
    {
      birdCode: 'LVB-214',
      name: 'Cinnamon Lovebird',
      slug: 'cinnamon-lovebird',
      species: 'Lovebird',
      variety: 'Cinnamon',
      color: 'Warm Cinnamon Brown Wings & Soft Green',
      age: '6.5 Months',
      gender: 'Male',
      price: 3600,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Clean beak.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix.',
      temperament: 'Gentle',
      description: 'Cinnamon mutation softening dark melanin into warm brownish feather tones.',
      images: JSON.stringify(['/images/birds/lvb_cinnamon.png']),
    },
    {
      birdCode: 'LVB-215',
      name: 'Seagreen Lovebird',
      slug: 'seagreen-lovebird',
      species: 'Lovebird',
      variety: 'Seagreen',
      color: 'Pastel Sea Green Body & Cream Mask',
      age: '5.5 Months',
      gender: 'Female',
      price: 3700,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Pastel seafoam feathers.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix & veggies.',
      temperament: 'Friendly',
      description: 'Blended seafoam green and ocean blue plumage with a soft pale cream mask.',
      images: JSON.stringify(['/images/birds/lvb_seagreen.png']),
    },
    {
      birdCode: 'LVB-216',
      name: 'Turquoise Lovebird',
      slug: 'turquoise-lovebird',
      species: 'Lovebird',
      variety: 'Turquoise',
      color: 'Deep Teal Turquoise Body & White Face',
      age: '6 Months',
      gender: 'Male',
      price: 3900,
      status: 'AVAILABLE',
      healthStatus: 'Show Quality',
      healthInfo: 'Vivid teal blue body.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix.',
      temperament: 'Active',
      description: 'Gorgeous teal-turquoise body with pure white forehead and throat.',
      images: JSON.stringify(['/images/birds/lvb_turquoise.png']),
    },
    {
      birdCode: 'LVB-217',
      name: 'Whiteface Lovebird',
      slug: 'whiteface-lovebird',
      species: 'Lovebird',
      variety: 'Whiteface',
      color: 'Immaculate White Face & Ocean Blue',
      age: '7 Months',
      gender: 'Female',
      price: 4100,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified',
      healthInfo: 'White facial mask.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix & egg food.',
      temperament: 'Affectionate',
      description: 'Eliminates yellow/red pigments for a clean white face mask over blue body.',
      images: JSON.stringify(['/images/birds/lvb_whiteface.png']),
    },
    {
      birdCode: 'LVB-218',
      name: 'Orange-face Lovebird',
      slug: 'orange-face-lovebird',
      species: 'Lovebird',
      variety: 'Orange-face',
      color: 'Vivid Tangerine Orange Mask & Green Body',
      age: '6 Months',
      gender: 'Male',
      price: 3800,
      status: 'AVAILABLE',
      healthStatus: 'Healthy',
      healthInfo: 'Tangerine mask.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix.',
      temperament: 'Playful',
      description: 'Replaces red facial mask with a bright tangerine-orange forehead.',
      images: JSON.stringify(['/images/birds/lvb_orange_face.png']),
    },
    {
      birdCode: 'LVB-220',
      name: 'Yellow-faced Lovebird',
      slug: 'yellow-faced-lovebird',
      species: 'Lovebird',
      variety: 'Yellow-faced',
      color: 'Lemon Yellow Mask & Sea Green Body',
      age: '6.5 Months',
      gender: 'Male',
      price: 4000,
      status: 'AVAILABLE',
      healthStatus: 'High Vitality',
      healthInfo: 'Lemon face contrast.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Fortified seed blend.',
      temperament: 'Vocal & Friendly',
      description: 'Blue series lovebird with a bright lemon yellow facial mask.',
      images: JSON.stringify(['/images/birds/lvb_yellow_faced.png']),
    },

    // --- 5 VERIFIED USER COCKATIEL VARIETIES ---
    {
      birdCode: 'CKT-301',
      name: 'Sunshine Lutino Cockatiel',
      slug: 'sunshine-lutino-cockatiel',
      species: 'Cockatiel',
      variety: 'Lutino',
      color: 'Yellow Head Crest & Bright Orange Cheek Spots',
      age: '7 Months',
      gender: 'Male',
      price: 4500,
      status: 'AVAILABLE',
      healthStatus: 'Whistling Melody Expert',
      healthInfo: 'Loves head scratches, whistles melodies.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Cockatiel seed mix, sunflower treats, calcium chew.',
      temperament: 'Highly Vocal & Gentle',
      description: 'Features iconic long yellow head crest and orange cheek patches. Whistles cheerful tunes when greeted.',
      images: JSON.stringify(['/images/birds/ckt_lutino.png']),
    },
    {
      birdCode: 'CKT-302',
      name: 'Classic Normal Grey Cockatiel',
      slug: 'classic-normal-grey-cockatiel',
      species: 'Cockatiel',
      variety: 'Normal Grey',
      color: 'Charcoal Grey Body, Yellow Face & Orange Cheeks',
      age: '8 Months',
      gender: 'Male',
      price: 4200,
      status: 'AVAILABLE',
      healthStatus: 'Vet Checked',
      healthInfo: 'Soft whistle sound, hand-tame.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Cockatiel blend + green veggies.',
      temperament: 'Sweet & Friendly',
      description: 'Classic ancestral Normal Grey Cockatiel with dark slate body, bright yellow face, and fiery orange cheek patches.',
      images: JSON.stringify(['/images/birds/ckt_normal_grey.png']),
    },
    {
      birdCode: 'CKT-303',
      name: 'Golden Pearl Cockatiel',
      slug: 'golden-pearl-cockatiel',
      species: 'Cockatiel',
      variety: 'Pearl',
      color: 'Scalloped Yellow & Charcoal Pearl Wing Lace',
      age: '6.5 Months',
      gender: 'Female',
      price: 4600,
      status: 'AVAILABLE',
      healthStatus: 'High Vitality',
      healthInfo: 'Intricate pearl wing lace.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Cockatiel seed mix.',
      temperament: 'Gentle & Quiet',
      description: 'Beautiful Pearl mutation exhibiting golden yellow scalloped lace patterns across grey wing feathers.',
      images: JSON.stringify(['/images/birds/ckt_pearl.png']),
    },
    {
      birdCode: 'CKT-304',
      name: 'Harlequin Pied Cockatiel',
      slug: 'harlequin-pied-cockatiel',
      species: 'Cockatiel',
      variety: 'Pied',
      color: 'Patchwork Buttercup Yellow & Slate Grey',
      age: '7.5 Months',
      gender: 'Male',
      price: 4700,
      status: 'AVAILABLE',
      healthStatus: 'Hand Tame',
      healthInfo: 'Asymmetrical pied patches.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Seed mix + sunflower.',
      temperament: 'Playful',
      description: 'Striking Pied mutation with random asymmetrical patches of buttercup yellow and white over slate body.',
      images: JSON.stringify(['/images/birds/ckt_pied.png']),
    },
    {
      birdCode: 'CKT-305',
      name: 'Pure Albino Whiteface Cockatiel',
      slug: 'pure-albino-whiteface-cockatiel',
      species: 'Cockatiel',
      variety: 'Albino Whiteface',
      color: 'Immaculate Snow White & Reddish Eyes',
      age: '8 Months',
      gender: 'Female',
      price: 5200,
      status: 'AVAILABLE',
      healthStatus: 'Rare Nursery Mutation',
      healthInfo: 'Immaculate white plumage.',
      careLevel: 'Intermediate',
      dietRecommendation: 'High protein seed + minerals.',
      temperament: 'Regal & Calm',
      description: 'Prized Albino Whiteface mutation completely free of yellow and orange pigments, presenting pure snow-white plumage.',
      images: JSON.stringify(['/images/birds/ckt_albino_whiteface.png']),
    },

    // --- 5 VERIFIED USER SUN CONURE VARIETIES ---
    {
      birdCode: 'SNC-401',
      name: 'Classic Normal Sun Conure (Rio)',
      slug: 'classic-normal-sun-conure-rio',
      species: 'Sun Conure',
      variety: 'Normal',
      color: 'Golden Yellow, Fiery Orange & Emerald Wings',
      age: '5 Months',
      gender: 'Male',
      price: 18500,
      status: 'AVAILABLE',
      healthStatus: 'DNA Sexed & Fully Tame',
      healthInfo: 'Hand-reared from hatchling, zero aggression, DNA sex certificate included.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Conure pellet diet, fresh papaya, nuts, seeds.',
      temperament: 'Extremely Cuddly & Playful Clown',
      description: 'Classic ancestral Sun Conure with fiery orange mask, golden yellow body, and sapphire-emerald wing tips.',
      images: JSON.stringify(['/images/birds/snc_normal.png']),
    },
    {
      birdCode: 'SNC-402',
      name: 'High Yellow Sun Conure',
      slug: 'high-yellow-sun-conure',
      species: 'Sun Conure',
      variety: 'High Yellow',
      color: 'Intense Lemon Yellow & Tangerine Orange',
      age: '6 Months',
      gender: 'Female',
      price: 19500,
      status: 'AVAILABLE',
      healthStatus: 'DNA Sexed Certified',
      healthInfo: 'Vivid high yellow back plumage.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Conure pellet blend & tropical fruits.',
      temperament: 'Vocal & Trick Learner',
      description: 'Selective breeding line displaying intense high yellow coverage across back mantle and wings.',
      images: JSON.stringify(['/images/birds/snc_high_yellow.png']),
    },
    {
      birdCode: 'SNC-403',
      name: 'Harlequin Pied Sun Conure',
      slug: 'harlequin-pied-sun-conure',
      species: 'Sun Conure',
      variety: 'Pied',
      color: 'Patchwork Golden Yellow & Emerald Green',
      age: '5.5 Months',
      gender: 'Male',
      price: 20500,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified',
      healthInfo: 'Rare pied feathering.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Nutritional pellets & seed mix.',
      temperament: 'Affectionate',
      description: 'Rare Pied mutation with asymmetrical patches of golden yellow intermingled with emerald wing feathers.',
      images: JSON.stringify(['/images/birds/snc_pied.png']),
    },
    {
      birdCode: 'SNC-404',
      name: 'White-beak Pied Sun Conure',
      slug: 'white-beak-pied-sun-conure',
      species: 'Sun Conure',
      variety: 'White-beak Pied',
      color: 'Ivory White Beak & Fiery Sunset Orange',
      age: '6.5 Months',
      gender: 'Female',
      price: 21500,
      status: 'AVAILABLE',
      healthStatus: 'Pedigree Breeder Line',
      healthInfo: 'Clean ivory horn beak.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Gourmet fruit pellet blend.',
      temperament: 'Sweet Companion',
      description: 'Exotic White-beak Pied mutation featuring a clean horn-white beak and fiery sunset plumage.',
      images: JSON.stringify(['/images/birds/snc_white_beak_pied.png']),
    },
    {
      birdCode: 'SNC-405',
      name: 'Yellow Pied Sun Conure',
      slug: 'yellow-pied-sun-conure',
      species: 'Sun Conure',
      variety: 'Yellow Pied',
      color: 'All Golden Yellow & Tangerine Crown',
      age: '7 Months',
      gender: 'Male',
      price: 22000,
      status: 'AVAILABLE',
      healthStatus: 'Hand-Fed Nursery Graduate',
      healthInfo: 'Loves cuddling, DNA sexed.',
      careLevel: 'Intermediate',
      dietRecommendation: 'High protein pellets & fresh corn.',
      temperament: 'Playful Cuddle Bug',
      description: 'Prized Yellow Pied Sun Conure with brilliant golden yellow body and vivid tangerine crown.',
      images: JSON.stringify(['/images/birds/snc_yellow_pied.png']),
    },

    // --- 3 VERIFIED USER FINCH VARIETIES ---
    {
      birdCode: 'FNC-501',
      name: 'Java Sparrow Finch',
      slug: 'java-sparrow-finch',
      species: 'Finch',
      variety: 'Java Sparrow',
      color: 'Silver Grey Body, Pink Beak & White Cheek Patches',
      age: '8 Months',
      gender: 'Male',
      price: 2600,
      status: 'AVAILABLE',
      healthStatus: 'Vet Certified',
      healthInfo: 'Plump frame, soft whistling chirp.',
      careLevel: 'Beginner',
      dietRecommendation: 'Finch seed mix & paddy rice.',
      temperament: 'Gentle & Peaceful',
      description: 'Charming Java Sparrow with smooth silver-grey plumage, bright pink beak, and white cheek patches.',
      images: JSON.stringify(['/images/birds/fnc_java_sparrow.png']),
    },
    {
      birdCode: 'FNC-502',
      name: 'Owl Finch (Double-barred Finch)',
      slug: 'owl-finch-double-barred-finch',
      species: 'Finch',
      variety: 'Owl Finch',
      color: 'White Face Mask with Double Black Chest Bars',
      age: '7.5 Months',
      gender: 'Female',
      price: 3400,
      status: 'AVAILABLE',
      healthStatus: 'High Vitality',
      healthInfo: 'Tiny owl facial disc.',
      careLevel: 'Intermediate',
      dietRecommendation: 'Small finch seeds & egg food.',
      temperament: 'Curious & Chirpy',
      description: 'Adorable Owl Finch featuring an owl-like white facial disc framed by distinctive double black chest bars.',
      images: JSON.stringify(['/images/birds/fnc_owl_finch.png']),
    },
    {
      birdCode: 'FNC-503',
      name: 'Pure Snow White Society Finch',
      slug: 'pure-snow-white-society-finch',
      species: 'Finch',
      variety: 'White Finch',
      color: 'Immaculate Snow White & Coral Beak',
      age: '6.5 Months',
      gender: 'Male',
      price: 2400,
      status: 'AVAILABLE',
      healthStatus: 'Active & Vocal',
      healthInfo: 'Chirps melodious tunes.',
      careLevel: 'Beginner',
      dietRecommendation: 'Finch seed blend & grit.',
      temperament: 'Social & Gentle',
      description: 'Immaculate pure snow-white Society Finch with soft coral pink beak and melodious singing habits.',
      images: JSON.stringify(['/images/birds/fnc_white_finch.jpg']),
    },
  ];

  for (const b of birdsData) {
    await prisma.bird.create({ data: b });
  }

  console.log('✅ Created 53 Birds covering 23 Budgies + 17 Lovebirds + 5 Cockatiels + 5 Sun Conures + 3 Finches!');

  // 6. Products (7 VERIFIED REAL CAGES + ACCESSORIES + NEW USER NESTS!)
  const productsData = [
    // --- USER REQUESTED NEST & NEST BOXES (FROM D:\pets\Acce\nest) ---
    {
      name: 'Handcrafted Jute Bird Nest for Cages & Breeding',
      slug: 'handcrafted-jute-bird-nest-for-cages-breeding',
      categoryId: accessoriesCat.id,
      brand: 'EcoNest',
      suitableFor: 'Budgies, Lovebirds, Finches, Canaries & Small Pet Birds',
      dimensions: '6 x 6 inches',
      material: '100% Organic Handcrafted Natural Jute Fiber',
      price: 249,
      discountPrice: 179,
      stock: 45,
      isFeatured: true,
      description: 'Warm handcrafted natural jute fiber bird nest designed for cages and breeding pairs. Provides natural insulation, egg safety, and a cozy roosting spot for small pet birds.',
      images: ['/images/products/nest_handcrafted_jute.jpg'],
    },
    {
      name: 'Earthen Clay Nesting Pots for Birds & Breeding',
      slug: 'earthen-clay-nesting-pots-for-birds-breeding',
      categoryId: accessoriesCat.id,
      brand: 'EcoNest Traditional',
      suitableFor: 'Budgies, Lovebirds, Cockatiels & Finches',
      dimensions: '7.5 inches diameter',
      material: '100% Natural Breathable Terra-Cotta Earthen Clay',
      price: 199,
      discountPrice: 149,
      stock: 50,
      isFeatured: true,
      description: 'Traditional breathable earthen clay nesting pots designed for bird breeding. Maintains optimal cool temperature and humidity for healthy egg hatching and chick nursery.',
      images: ['/images/products/nest_clay_pots.jpg'],
    },

    // --- 7 VERIFIED REAL CAGES ONLY FROM D:\pets\Acce\cage ---
    {
      name: 'Bird Transport Cage (House Shape Powder Coated)',
      slug: 'bird-transport-cage-house-shape-powder-coated',
      categoryId: cagesCat.id,
      brand: 'Pet Bar Barky',
      suitableFor: 'Multipurpose Small Pet Birds (Budgies, Finches, Canaries, Lovebirds)',
      dimensions: '21 x 20 x 26 cm',
      material: 'Aluminium Sheet & Powder-Coated Iron Wire',
      price: 180,
      discountPrice: 110,
      stock: 50,
      isFeatured: true,
      description: 'Compact house-shaped multipurpose bird transport cage crafted with aluminium sheet base and strong, lightweight powder-coated iron wire. Features hanging roof hook, single entry door, and easy carrying portability.',
      images: ['/images/products/cage_transport_house.webp'],
    },
    {
      name: 'Birds Mild Steel Pink Travel Bird Cage (1 ft)',
      slug: 'birds-mild-steel-pink-travel-bird-cage-1ft',
      categoryId: cagesCat.id,
      brand: 'Pet Bar Barky',
      suitableFor: 'All Small Pet Birds (Budgies, Lovebirds, Finches, Canaries)',
      dimensions: '1 ft (12 x 10 x 12 inches)',
      material: 'Mild Steel Wire',
      price: 350,
      discountPrice: 250,
      stock: 40,
      isFeatured: true,
      description: 'Compact 1-foot pink mild steel bird cage designed for home purpose and travel transport. Features top carrying handle, secure door latch, food cup holders, and easy-clean base.',
      images: ['/images/products/cage_pink_travel_1ft.jpg'],
    },
    {
      name: 'Compact Small Pet Bird Cage (~18 × 12 × 15 Inch)',
      slug: 'compact-small-pet-bird-cage-18x12x15',
      categoryId: cagesCat.id,
      brand: 'Pet Bar Barky',
      suitableFor: '1 Finch, Canary, Small Budgie & Small Pet Birds',
      dimensions: '18 × 12 × 15 inches (~45 x 30 x 38 cm)',
      material: 'Non-Toxic Powder-Coated Metal Wire',
      price: 999,
      discountPrice: 799,
      stock: 25,
      isFeatured: true,
      description: 'Compact small starter bird cage measuring ~18 × 12 × 15 inches designed specifically for 1 Finch, Canary, or small Budgie. Features food/water cups, perches, and an easy-clean pull-out tray.',
      images: ['/images/products/cage_small_18x12x15.png'],
    },
    {
      name: 'Medium Pet Bird Cage (~30 × 18 × 24 Inch)',
      slug: 'medium-pet-bird-cage-30x18x24',
      categoryId: cagesCat.id,
      brand: 'Pet Bar Barky',
      suitableFor: 'Multiple Budgies, Lovebirds, Small Cockatiels',
      dimensions: '~30 × 18 × 24 inches (76 x 45 x 60 cm)',
      material: 'Non-Toxic Powder-Coated Metal Wire',
      price: 2299,
      discountPrice: 1899,
      stock: 20,
      isFeatured: true,
      description: 'Spacious medium indoor bird cage measuring ~30 × 18 × 24 inches designed specifically for multiple Budgies, Lovebirds, or small Cockatiels. Features multi-door entry access, wooden perches, feeder cups, and removable waste drawer tray.',
      images: ['/images/products/cage_medium_30x18x24.png'],
    },
    {
      name: '2 Feet Pink Metal Bird Cage (Comfortable, Secure & Spacious)',
      slug: '2-feet-pink-metal-bird-cage',
      categoryId: cagesCat.id,
      brand: 'Pet Bar Barky',
      suitableFor: 'Budgies, Lovebirds, Cockatiels, Finches',
      dimensions: '76.2L x 60W x 7H cm (30 x 24 x 2.7 inches)',
      material: 'Non-Toxic Powder-Coated Metal Wire',
      price: 2499,
      discountPrice: 1999,
      stock: 15,
      isFeatured: true,
      description: 'Spacious 2-foot indoor pink metal bird cage featuring comfortable wooden perches, secure safety door latch, removable waste drawer tray, and heavy-duty metal wire body.',
      images: ['/images/products/cage_2ft_pink.jpg'],
    },
    {
      name: 'Customised Aviary Multi-Door Bird Cage',
      slug: 'customised-aviary-multi-door-bird-cage',
      categoryId: cagesCat.id,
      brand: 'AviaryPro Custom',
      suitableFor: 'Budgies, Lovebirds, Cockatiels & Conures',
      dimensions: '28 x 20 x 32 inches',
      material: 'Heavy-Duty Galvanized Powder-Coated Steel Wire',
      price: 3899,
      discountPrice: 3299,
      stock: 12,
      isFeatured: true,
      description: 'Customised aviary bird cage featuring multi-door breeding ports, removable waste tray, feeder access doors, and heavy-duty wire mesh construction.',
      images: ['/images/products/cage_customised_aviary.jpg'],
    },
    {
      name: 'Heavy-Duty Rust-Proof Stainless Steel Bird Cage',
      slug: 'heavy-duty-rust-proof-stainless-steel-bird-cage',
      categoryId: cagesCat.id,
      brand: 'AviaryPro Premium',
      suitableFor: 'Budgies, Lovebirds, Cockatiels, Conures',
      dimensions: '24 x 20 x 36 inches',
      material: '100% Medical-Grade Rust-Proof Stainless Steel',
      price: 5499,
      discountPrice: 4699,
      stock: 10,
      isFeatured: true,
      description: 'Premium 100% medical-grade stainless steel bird cage engineered for lifetime durability with double safety door locks, stainless feeding bowls, and removable waste drawer.',
      images: ['/images/products/cage_stainless_steel.jpg'],
    },

    // --- 5 VERIFIED TOYS & SWINGS (FROM D:\pets\Acce\toys) ---
    {
      name: 'Natural Wooden Chewing Activity Swing & Shredding Toy',
      slug: 'natural-wooden-chewing-activity-swing-shredding-toy',
      categoryId: accessoriesCat.id,
      brand: 'ChirpJoy Natural',
      suitableFor: 'Lovebirds, Cockatiels, Conures, Parakeets & Parrots',
      dimensions: '12 x 10 inches',
      material: 'Natural Hardwood Branches, Wood Slices, Colored Chewing Blocks & Loofah Rings',
      price: 499,
      discountPrice: 399,
      stock: 35,
      isFeatured: true,
      description: 'Multi-functional activity swing featuring natural hardwood branch perches, colorful wood chew blocks, rattan balls, loofah shredding rings, and bells. Encourages healthy beak trimming and satisfies natural chewing and foraging instincts.',
      images: ['/images/products/toy_chewing_swing.jpg'],
    },
    {
      name: 'Arch Wooden Bead Bell Swing with Natural Perch (D-Swing)',
      slug: 'arch-wooden-bead-bell-swing-d-swing',
      categoryId: accessoriesCat.id,
      brand: 'ChirpJoy',
      suitableFor: 'Budgies, Lovebirds, Finches, Canaries & Small Birds',
      dimensions: '8 x 6 inches',
      material: 'Natural Bark Tree Branch Perch, Non-Toxic Colored Wooden Beads, Chime Bells',
      price: 199,
      discountPrice: 149,
      stock: 50,
      isFeatured: true,
      description: 'Classic arch-shaped D-swing crafted with a textured natural bark perch bar, colorful wooden beads, and pleasant chime bells. Perfect for budgies and lovebirds to swing, roost, and exercise foot grip.',
      images: ['/images/products/toy_dswing.png'],
    },
    {
      name: '2-Tier Natural Wood Branch Hanging Rope Perch Swing',
      slug: '2-tier-natural-wood-branch-hanging-rope-perch-swing',
      categoryId: accessoriesCat.id,
      brand: 'AviaryCraft',
      suitableFor: 'Budgies, Cockatiels, Conures & Parrots',
      dimensions: '18 x 8 inches',
      material: 'Natural Hardwood Branch Perches & 100% Organic Cotton Rope with Metal Hanging Carabiner',
      price: 399,
      discountPrice: 299,
      stock: 30,
      isFeatured: true,
      description: 'Two-tier vertical climbing and resting swing crafted with rustic natural branch perches and durable organic cotton rope. Accommodates multiple birds simultaneously and offers great acrobatic exercise.',
      images: ['/images/products/toy_two_tier_rope_swing.jpg'],
    },
    {
      name: 'Wide Budgie & Parakeet Wooden Perch Swing with Colorful Beads',
      slug: 'wide-budgie-parakeet-wooden-perch-swing-colorful-beads',
      categoryId: accessoriesCat.id,
      brand: 'ChirpJoy',
      suitableFor: 'Budgies, Parakeets, Lovebirds & Finches (Flock Friendly)',
      dimensions: '10 x 8 inches',
      material: 'Smooth Natural Wood Perch Dowel, Vibrant Wooden Beads & Dual Metal Cage Hooks',
      price: 249,
      discountPrice: 189,
      stock: 45,
      isFeatured: true,
      description: 'Wide flock-friendly horizontal swing featuring colorful bead suspension bars and dual heavy-duty cage hooks. Wide enough for up to 4 budgies to swing, socialize, and perch together comfortably.',
      images: ['/images/products/toy_budgie_wooden_swing.jpg'],
    },
    {
      name: 'Suspended Wooden Ladder Platform Swing with Metal Chains',
      slug: 'suspended-wooden-ladder-platform-swing-metal-chains',
      categoryId: accessoriesCat.id,
      brand: 'ChirpJoy',
      suitableFor: 'Budgies, Lovebirds, Cockatiels & Small Pets',
      dimensions: '8 x 6 x 8 inches',
      material: 'Natural Wood Ladder Rungs, Colorful Spacer Beads, Rust-Resistant Hanging Chains',
      price: 279,
      discountPrice: 219,
      stock: 40,
      isFeatured: true,
      description: 'Four-chain suspended wooden ladder bridge and platform swing. Provides a fun horizontal climbing, swinging, and perching surface decorated with colorful beads to stimulate agility and balance.',
      images: ['/images/products/toy_wooden_ladder_bridge.jpg'],
    },
    // --- VERIFIED CUTTLEFISH & CALCIUM (FROM D:\pets\Acce\cattle fish and calcium) ---
    {
      name: 'Pure Natural Cuttlefish Bone for Birds (Pack of 4)',
      slug: 'pure-natural-cuttlefish-bone-for-birds-pack-of-4',
      categoryId: accessoriesCat.id,
      brand: 'FeatherNourish Natural',
      suitableFor: 'Budgies, Cockatiels, Lovebirds, Finches, Canaries & Parrots',
      packageWeight: '4 Whole Natural Cuttlefish Bones with Metal Holders',
      ingredients: '100% Pure Natural Sun-Dried Cuttlefish Bone (Organic Calcium & Minerals)',
      dimensions: '6 to 8 inches each',
      material: '100% Organic Cuttlefish Bone',
      price: 199,
      discountPrice: 149,
      stock: 60,
      isFeatured: true,
      description: '100% natural, sun-dried pure cuttlefish bones. An essential organic source of bio-available calcium, phosphorus, and trace minerals for eggshell formation, strong bones, and healthy natural beak trimming.',
      images: ['/images/products/cuttlefish_bone_natural.webp'],
    },
    {
      name: 'Hanging Mineral Calcium Block for Pet Birds with Cage Clip',
      slug: 'hanging-mineral-calcium-block-for-pet-birds-cage-clip',
      categoryId: accessoriesCat.id,
      brand: 'FeatherNourish',
      suitableFor: 'Budgies, Lovebirds, Cockatiels, Finches & Small Pet Birds',
      packageWeight: '120g Molded Calcium Cup',
      ingredients: 'Calcium Carbonate, Shell Grit, Essential Trace Minerals & Natural Binder',
      dimensions: '3 x 3 x 2.5 inches with Hanging Clip',
      material: 'Mineral Calcium Block with Cage Bar Clip',
      price: 149,
      discountPrice: 99,
      stock: 50,
      isFeatured: true,
      description: 'Fluted hanging calcium and mineral supplement block with built-in attachment hook for easy cage bar mounting. Enriched with calcium, minerals, and grit for healthy beak conditioning and vitality.',
      images: ['/images/products/hanging_calcium_mineral_block.jpg'],
    },

    // --- 2 VERIFIED FOOD & SEED PRODUCTS (FROM D:\pets\Acce\seed & D:\pets\Acce\seed_mix) ---
    {
      name: 'Avigrain Budgie Grain & Seed Diet (1kg)',
      slug: 'avigrain-budgie-grain-seed-diet-1kg',
      categoryId: foodCat.id,
      brand: 'Avigrain',
      suitableFor: 'Budgies, Small Parakeets, Lovebirds & Finches',
      packageWeight: '1 kg',
      ingredients: 'Cleaned French White Millet, Panorama Millet, Panicum, Plain Canary Seed & Red Millet',
      dimensions: '1kg Sealed Barrier Pouch',
      material: '100% Natural Selected Grains',
      price: 299,
      discountPrice: 249,
      stock: 50,
      isFeatured: true,
      description: 'Premium Australian Avigrain style seed blend, triple-cleaned and dust-extracted. High in wholesome natural energy and essential carbs for daily pet bird vitality.',
      images: ['/images/products/seed_avigrain_budgie_mix.jpg'],
    },
    {
      name: '11-in-1 Fortified Multi-Seed Mix for Budgies & Cockatiels (1kg)',
      slug: '11-in-1-fortified-multi-seed-mix-budgies-cockatiels-1kg',
      categoryId: foodCat.id,
      brand: 'Avian Gourmet',
      suitableFor: 'Budgies, Cockatiels, Lovebirds, Conures & Parrots',
      packageWeight: '1 kg',
      ingredients: '11-15 Grains including Striped Sunflower Seeds, Safflower, Whole Oat Groats, Red Millet, Yellow Millet, Flaxseed, Buckwheat & Canary Seed',
      dimensions: '1kg Heavy Moisture-Lock Pouch',
      material: '11 to 15 Whole Seed & Grain Varieties',
      price: 399,
      discountPrice: 329,
      stock: 45,
      isFeatured: true,
      description: 'Specialty fortified multi-seed mix blend combining 11 to 15 diverse grains, sunflower seeds, and groats. Packed with healthy fats, fatty acids, and proteins to support feather luster and overall plumage health.',
      images: ['/images/products/seed_mix_11_15_grains.webp'],
    },
  ];

  for (const p of productsData) {
    const images = p.images;
    delete (p as any).images;

    await prisma.product.create({
      data: {
        ...p,
        images: {
          create: images.map((url, idx) => ({
            url,
            isPrimary: idx === 0,
          })),
        },
      },
    });
  }

  // 7. Coupons
  await prisma.coupon.create({
    data: {
      code: 'WELCOME10',
      type: 'PERCENTAGE',
      value: 10,
      minOrderAmount: 500,
      maxDiscount: 500,
      isActive: true,
    },
  });

  // 8. Blog Posts
  const guides = [
    {
      title: 'How to Care for Your New Finch, Budgie & Lovebird: Complete Guide',
      slug: 'how-to-care-for-your-new-budgie',
      category: 'Beginner Care',
      excerpt: 'Bringing home Finches, Budgies, Lovebirds, or Cockatiels? Learn cage setup, diet essentials, and flight routines.',
      content: `### Welcoming Your Feathered Companions Home...`,
      readTime: '5 min read',
      image: '/images/birds/fnc_java_sparrow.png',
    },
    {
      title: 'Pet Bar Barky Bird Cage Setup & Breeding Nest Box Guide',
      slug: 'pet-bar-barky-bird-cage-setup-guide',
      category: 'Cages & Breeding',
      excerpt: 'Learn how to choose and set up Pet Bar Barky cages, wooden nest boxes, interactive toys, and perches for breeding pairs.',
      content: `### Choosing Pet Bar Barky Cages & Accessories...`,
      readTime: '6 min read',
      image: '/images/products/nest_handcrafted_jute.jpg',
    },
  ];

  for (const g of guides) {
    await prisma.blogPost.create({ data: g });
  }

  console.log('🎉 Database Seed Completed Successfully with Jute Nest & Earthen Clay Nesting Pots!');
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
